### ISSUE TITLE
1.0.13 breaks current stable Haraka (2.8.16)

### ISSUE THREAD

**Issue by smfreegard** [haraka/haraka-net-utils#33]
Reported by EyePulp on IRC:

2018-01-25T21:34:36.566Z :: [CRIT] [-] [core] TypeError: net_utils.tls_ini_section_with_defaults is not a function
2018-01-25T21:34:36.567Z :: [CRIT] [-] [core]     at Object.exports.get_tls_options (/var/projects/kaczynski/bin/haraka_installer/node_modules/Haraka/outbound/tls.js:10:35)
2018-01-25T21:34:36.568Z :: [CRIT] [-] [core]     at pluggableStream.<anonymous> (/var/projects/kaczynski/bin/haraka_installer/node_modules/Haraka/outbound/hmail.js:774:51)
2018-01-25T21:34:36.569Z :: [CRIT] [-] [core]     at emitOne (events.js:96:13)
2018-01-25T21:34:36.572Z :: [CRIT] [-] [core]     at pluggableStream.emit (events.js:188:7)
2018-01-25T21:34:36.572Z :: [CRIT] [-] [core]     at pluggableStream.socket.process_data (/var/projects/kaczynski/bin/haraka_installer/node_modules/Haraka/line_socket.js:24:20)
2018-01-25T21:34:36.573Z :: [CRIT] [-] [core]     at pluggableStream.<anonymous> (/var/projects/kaczynski/bin/haraka_installer/node_modules/Haraka/line_socket.js:35:48)
2018-01-25T21:34:36.573Z :: [CRIT] [-] [core]     at emitOne (events.js:96:13)
2018-01-25T21:34:36.573Z :: [CRIT] [-] [core]     at pluggableStream.emit (events.js:188:7)
2018-01-25T21:34:36.574Z :: [CRIT] [-] [core]     at Socket.<anonymous> (/var/projects/kaczynski/bin/haraka_installer/node_modules/Haraka/tls_socket.js:57:14)
2018-01-25T21:34:36.575Z :: [CRIT] [-] [core]     at emitOne (events.js:96:13)

Because Haraka's package.json contains:

 "dependencies": {
    "haraka-net-utils"      : ">=1.0.10",
  },

And https://github.com/haraka/haraka-net-utils/commit/e1c8e8bd68be092638f19102fd1bc94554b6d426 breaks it.

Maybe we should pin versions for release in future to prevent things like this from happening?

Cc: @baudehlo

**Comment by baudehlo** [comment]
By semver rules that change should never have gone out.

**Comment by smfreegard** [comment]
Typo on my part.... it's late here.   1.0.13 not 10.0.13

**Comment by smfreegard** [comment]
I've just had another person on IRC with the same issue.   Fix is: `cd /path/to/lib/node_modules/Haraka && npm install haraka-net-utils@1.0.10`

**Comment by msimerson** [comment]
Dang, it's been so long since a release... I should have browsed back versions of Haraka instead of going from memory. I **thought** that wasn't  a required function. I will:
- restore tls_ini_section_with_defaults
- publish 1.0.14
- unpublish 1.0.13

**Comment by smfreegard** [comment]
Thanks - it happens - the dependencies have become quite complicated.
